// @generated por scripts/build-flags.mjs — no editar a mano.
// Para cambiar países, continentes o dificultades, edita el script y vuelve a
// ejecutarlo: node scripts/build-flags.mjs

export type Continent = 'europa' | 'america' | 'africa' | 'asia' | 'oceania';

export interface Country {
  /** ISO 3166-1 alpha-2, en mayúsculas. */
  cc: string;
  continent: Continent;
  /** 1 = conocida, 2 = intermedia, 3 = difícil. */
  difficulty: 1 | 2 | 3;
  name: { es: string; en: string };
}

export const CONTINENTS: Continent[] = ['europa', 'america', 'africa', 'asia', 'oceania'];

/** Emoji de bandera a partir del código ISO (pares de indicadores regionales). */
export function flagEmoji(cc: string): string {
  return String.fromCodePoint(
    ...cc.toUpperCase().split('').map(ch => 0x1f1e6 + ch.charCodeAt(0) - 65),
  );
}

export const COUNTRIES: Country[] = [
  { cc: 'AD', continent: 'europa', difficulty: 2, name: { es: "Andorra", en: "Andorra" } },
  { cc: 'AE', continent: 'asia', difficulty: 2, name: { es: "Emiratos Árabes Unidos", en: "United Arab Emirates" } },
  { cc: 'AF', continent: 'asia', difficulty: 2, name: { es: "Afganistán", en: "Afghanistan" } },
  { cc: 'AG', continent: 'america', difficulty: 3, name: { es: "Antigua y Barbuda", en: "Antigua and Barbuda" } },
  { cc: 'AL', continent: 'europa', difficulty: 2, name: { es: "Albania", en: "Albania" } },
  { cc: 'AM', continent: 'asia', difficulty: 2, name: { es: "Armenia", en: "Armenia" } },
  { cc: 'AO', continent: 'africa', difficulty: 2, name: { es: "Angola", en: "Angola" } },
  { cc: 'AR', continent: 'america', difficulty: 1, name: { es: "Argentina", en: "Argentina" } },
  { cc: 'AT', continent: 'europa', difficulty: 1, name: { es: "Austria", en: "Austria" } },
  { cc: 'AU', continent: 'oceania', difficulty: 1, name: { es: "Australia", en: "Australia" } },
  { cc: 'AZ', continent: 'asia', difficulty: 3, name: { es: "Azerbaiyán", en: "Azerbaijan" } },
  { cc: 'BA', continent: 'europa', difficulty: 2, name: { es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina" } },
  { cc: 'BB', continent: 'america', difficulty: 3, name: { es: "Barbados", en: "Barbados" } },
  { cc: 'BD', continent: 'asia', difficulty: 2, name: { es: "Bangladés", en: "Bangladesh" } },
  { cc: 'BE', continent: 'europa', difficulty: 1, name: { es: "Bélgica", en: "Belgium" } },
  { cc: 'BF', continent: 'africa', difficulty: 3, name: { es: "Burkina Faso", en: "Burkina Faso" } },
  { cc: 'BG', continent: 'europa', difficulty: 2, name: { es: "Bulgaria", en: "Bulgaria" } },
  { cc: 'BH', continent: 'asia', difficulty: 3, name: { es: "Baréin", en: "Bahrain" } },
  { cc: 'BI', continent: 'africa', difficulty: 3, name: { es: "Burundi", en: "Burundi" } },
  { cc: 'BJ', continent: 'africa', difficulty: 3, name: { es: "Benín", en: "Benin" } },
  { cc: 'BN', continent: 'asia', difficulty: 3, name: { es: "Brunéi", en: "Brunei" } },
  { cc: 'BO', continent: 'america', difficulty: 2, name: { es: "Bolivia", en: "Bolivia" } },
  { cc: 'BR', continent: 'america', difficulty: 1, name: { es: "Brasil", en: "Brazil" } },
  { cc: 'BS', continent: 'america', difficulty: 3, name: { es: "Bahamas", en: "Bahamas" } },
  { cc: 'BT', continent: 'asia', difficulty: 3, name: { es: "Bután", en: "Bhutan" } },
  { cc: 'BW', continent: 'africa', difficulty: 3, name: { es: "Botsuana", en: "Botswana" } },
  { cc: 'BY', continent: 'europa', difficulty: 2, name: { es: "Bielorrusia", en: "Belarus" } },
  { cc: 'BZ', continent: 'america', difficulty: 3, name: { es: "Belice", en: "Belize" } },
  { cc: 'CA', continent: 'america', difficulty: 1, name: { es: "Canadá", en: "Canada" } },
  { cc: 'CD', continent: 'africa', difficulty: 3, name: { es: "República Democrática del Congo", en: "DR Congo" } },
  { cc: 'CF', continent: 'africa', difficulty: 3, name: { es: "República Centroafricana", en: "Central African Republic" } },
  { cc: 'CG', continent: 'africa', difficulty: 3, name: { es: "República del Congo", en: "Republic of the Congo" } },
  { cc: 'CH', continent: 'europa', difficulty: 1, name: { es: "Suiza", en: "Switzerland" } },
  { cc: 'CI', continent: 'africa', difficulty: 2, name: { es: "Côte d’Ivoire", en: "Côte d’Ivoire" } },
  { cc: 'CL', continent: 'america', difficulty: 1, name: { es: "Chile", en: "Chile" } },
  { cc: 'CM', continent: 'africa', difficulty: 2, name: { es: "Camerún", en: "Cameroon" } },
  { cc: 'CN', continent: 'asia', difficulty: 1, name: { es: "China", en: "China" } },
  { cc: 'CO', continent: 'america', difficulty: 1, name: { es: "Colombia", en: "Colombia" } },
  { cc: 'CR', continent: 'america', difficulty: 2, name: { es: "Costa Rica", en: "Costa Rica" } },
  { cc: 'CU', continent: 'america', difficulty: 1, name: { es: "Cuba", en: "Cuba" } },
  { cc: 'CV', continent: 'africa', difficulty: 3, name: { es: "Cabo Verde", en: "Cape Verde" } },
  { cc: 'CY', continent: 'europa', difficulty: 2, name: { es: "Chipre", en: "Cyprus" } },
  { cc: 'CZ', continent: 'europa', difficulty: 2, name: { es: "Chequia", en: "Czechia" } },
  { cc: 'DE', continent: 'europa', difficulty: 1, name: { es: "Alemania", en: "Germany" } },
  { cc: 'DJ', continent: 'africa', difficulty: 3, name: { es: "Yibuti", en: "Djibouti" } },
  { cc: 'DK', continent: 'europa', difficulty: 1, name: { es: "Dinamarca", en: "Denmark" } },
  { cc: 'DM', continent: 'america', difficulty: 3, name: { es: "Dominica", en: "Dominica" } },
  { cc: 'DO', continent: 'america', difficulty: 2, name: { es: "República Dominicana", en: "Dominican Republic" } },
  { cc: 'DZ', continent: 'africa', difficulty: 2, name: { es: "Argelia", en: "Algeria" } },
  { cc: 'EC', continent: 'america', difficulty: 2, name: { es: "Ecuador", en: "Ecuador" } },
  { cc: 'EE', continent: 'europa', difficulty: 2, name: { es: "Estonia", en: "Estonia" } },
  { cc: 'EG', continent: 'africa', difficulty: 1, name: { es: "Egipto", en: "Egypt" } },
  { cc: 'ER', continent: 'africa', difficulty: 3, name: { es: "Eritrea", en: "Eritrea" } },
  { cc: 'ES', continent: 'europa', difficulty: 1, name: { es: "España", en: "Spain" } },
  { cc: 'ET', continent: 'africa', difficulty: 2, name: { es: "Etiopía", en: "Ethiopia" } },
  { cc: 'FI', continent: 'europa', difficulty: 1, name: { es: "Finlandia", en: "Finland" } },
  { cc: 'FJ', continent: 'oceania', difficulty: 2, name: { es: "Fiyi", en: "Fiji" } },
  { cc: 'FM', continent: 'oceania', difficulty: 3, name: { es: "Micronesia", en: "Micronesia" } },
  { cc: 'FR', continent: 'europa', difficulty: 1, name: { es: "Francia", en: "France" } },
  { cc: 'GA', continent: 'africa', difficulty: 3, name: { es: "Gabón", en: "Gabon" } },
  { cc: 'GB', continent: 'europa', difficulty: 1, name: { es: "Reino Unido", en: "United Kingdom" } },
  { cc: 'GD', continent: 'america', difficulty: 3, name: { es: "Granada", en: "Grenada" } },
  { cc: 'GE', continent: 'asia', difficulty: 2, name: { es: "Georgia", en: "Georgia" } },
  { cc: 'GH', continent: 'africa', difficulty: 2, name: { es: "Ghana", en: "Ghana" } },
  { cc: 'GM', continent: 'africa', difficulty: 3, name: { es: "Gambia", en: "Gambia" } },
  { cc: 'GN', continent: 'africa', difficulty: 3, name: { es: "Guinea", en: "Guinea" } },
  { cc: 'GQ', continent: 'africa', difficulty: 3, name: { es: "Guinea Ecuatorial", en: "Equatorial Guinea" } },
  { cc: 'GR', continent: 'europa', difficulty: 1, name: { es: "Grecia", en: "Greece" } },
  { cc: 'GT', continent: 'america', difficulty: 2, name: { es: "Guatemala", en: "Guatemala" } },
  { cc: 'GW', continent: 'africa', difficulty: 3, name: { es: "Guinea-Bisáu", en: "Guinea-Bissau" } },
  { cc: 'GY', continent: 'america', difficulty: 3, name: { es: "Guyana", en: "Guyana" } },
  { cc: 'HN', continent: 'america', difficulty: 2, name: { es: "Honduras", en: "Honduras" } },
  { cc: 'HR', continent: 'europa', difficulty: 2, name: { es: "Croacia", en: "Croatia" } },
  { cc: 'HT', continent: 'america', difficulty: 2, name: { es: "Haití", en: "Haiti" } },
  { cc: 'HU', continent: 'europa', difficulty: 2, name: { es: "Hungría", en: "Hungary" } },
  { cc: 'ID', continent: 'asia', difficulty: 2, name: { es: "Indonesia", en: "Indonesia" } },
  { cc: 'IE', continent: 'europa', difficulty: 1, name: { es: "Irlanda", en: "Ireland" } },
  { cc: 'IL', continent: 'asia', difficulty: 1, name: { es: "Israel", en: "Israel" } },
  { cc: 'IN', continent: 'asia', difficulty: 1, name: { es: "India", en: "India" } },
  { cc: 'IQ', continent: 'asia', difficulty: 2, name: { es: "Irak", en: "Iraq" } },
  { cc: 'IR', continent: 'asia', difficulty: 2, name: { es: "Irán", en: "Iran" } },
  { cc: 'IS', continent: 'europa', difficulty: 2, name: { es: "Islandia", en: "Iceland" } },
  { cc: 'IT', continent: 'europa', difficulty: 1, name: { es: "Italia", en: "Italy" } },
  { cc: 'JM', continent: 'america', difficulty: 2, name: { es: "Jamaica", en: "Jamaica" } },
  { cc: 'JO', continent: 'asia', difficulty: 2, name: { es: "Jordania", en: "Jordan" } },
  { cc: 'JP', continent: 'asia', difficulty: 1, name: { es: "Japón", en: "Japan" } },
  { cc: 'KE', continent: 'africa', difficulty: 1, name: { es: "Kenia", en: "Kenya" } },
  { cc: 'KG', continent: 'asia', difficulty: 3, name: { es: "Kirguistán", en: "Kyrgyzstan" } },
  { cc: 'KH', continent: 'asia', difficulty: 2, name: { es: "Camboya", en: "Cambodia" } },
  { cc: 'KI', continent: 'oceania', difficulty: 3, name: { es: "Kiribati", en: "Kiribati" } },
  { cc: 'KM', continent: 'africa', difficulty: 3, name: { es: "Comoras", en: "Comoros" } },
  { cc: 'KN', continent: 'america', difficulty: 3, name: { es: "San Cristóbal y Nieves", en: "Saint Kitts and Nevis" } },
  { cc: 'KP', continent: 'asia', difficulty: 2, name: { es: "Corea del Norte", en: "North Korea" } },
  { cc: 'KR', continent: 'asia', difficulty: 1, name: { es: "Corea del Sur", en: "South Korea" } },
  { cc: 'KW', continent: 'asia', difficulty: 2, name: { es: "Kuwait", en: "Kuwait" } },
  { cc: 'KZ', continent: 'asia', difficulty: 2, name: { es: "Kazajistán", en: "Kazakhstan" } },
  { cc: 'LA', continent: 'asia', difficulty: 3, name: { es: "Laos", en: "Laos" } },
  { cc: 'LB', continent: 'asia', difficulty: 2, name: { es: "Líbano", en: "Lebanon" } },
  { cc: 'LC', continent: 'america', difficulty: 3, name: { es: "Santa Lucía", en: "St. Lucia" } },
  { cc: 'LI', continent: 'europa', difficulty: 3, name: { es: "Liechtenstein", en: "Liechtenstein" } },
  { cc: 'LK', continent: 'asia', difficulty: 2, name: { es: "Sri Lanka", en: "Sri Lanka" } },
  { cc: 'LR', continent: 'africa', difficulty: 3, name: { es: "Liberia", en: "Liberia" } },
  { cc: 'LS', continent: 'africa', difficulty: 3, name: { es: "Lesoto", en: "Lesotho" } },
  { cc: 'LT', continent: 'europa', difficulty: 2, name: { es: "Lituania", en: "Lithuania" } },
  { cc: 'LU', continent: 'europa', difficulty: 2, name: { es: "Luxemburgo", en: "Luxembourg" } },
  { cc: 'LV', continent: 'europa', difficulty: 2, name: { es: "Letonia", en: "Latvia" } },
  { cc: 'LY', continent: 'africa', difficulty: 2, name: { es: "Libia", en: "Libya" } },
  { cc: 'MA', continent: 'africa', difficulty: 1, name: { es: "Marruecos", en: "Morocco" } },
  { cc: 'MC', continent: 'europa', difficulty: 2, name: { es: "Mónaco", en: "Monaco" } },
  { cc: 'MD', continent: 'europa', difficulty: 3, name: { es: "Moldavia", en: "Moldova" } },
  { cc: 'ME', continent: 'europa', difficulty: 2, name: { es: "Montenegro", en: "Montenegro" } },
  { cc: 'MG', continent: 'africa', difficulty: 2, name: { es: "Madagascar", en: "Madagascar" } },
  { cc: 'MH', continent: 'oceania', difficulty: 3, name: { es: "Islas Marshall", en: "Marshall Islands" } },
  { cc: 'MK', continent: 'europa', difficulty: 2, name: { es: "Macedonia del Norte", en: "North Macedonia" } },
  { cc: 'ML', continent: 'africa', difficulty: 3, name: { es: "Mali", en: "Mali" } },
  { cc: 'MM', continent: 'asia', difficulty: 2, name: { es: "Myanmar", en: "Myanmar" } },
  { cc: 'MN', continent: 'asia', difficulty: 2, name: { es: "Mongolia", en: "Mongolia" } },
  { cc: 'MR', continent: 'africa', difficulty: 3, name: { es: "Mauritania", en: "Mauritania" } },
  { cc: 'MT', continent: 'europa', difficulty: 2, name: { es: "Malta", en: "Malta" } },
  { cc: 'MU', continent: 'africa', difficulty: 3, name: { es: "Mauricio", en: "Mauritius" } },
  { cc: 'MV', continent: 'asia', difficulty: 3, name: { es: "Maldivas", en: "Maldives" } },
  { cc: 'MW', continent: 'africa', difficulty: 3, name: { es: "Malaui", en: "Malawi" } },
  { cc: 'MX', continent: 'america', difficulty: 1, name: { es: "México", en: "Mexico" } },
  { cc: 'MY', continent: 'asia', difficulty: 2, name: { es: "Malasia", en: "Malaysia" } },
  { cc: 'MZ', continent: 'africa', difficulty: 2, name: { es: "Mozambique", en: "Mozambique" } },
  { cc: 'NA', continent: 'africa', difficulty: 3, name: { es: "Namibia", en: "Namibia" } },
  { cc: 'NE', continent: 'africa', difficulty: 3, name: { es: "Níger", en: "Niger" } },
  { cc: 'NG', continent: 'africa', difficulty: 1, name: { es: "Nigeria", en: "Nigeria" } },
  { cc: 'NI', continent: 'america', difficulty: 2, name: { es: "Nicaragua", en: "Nicaragua" } },
  { cc: 'NL', continent: 'europa', difficulty: 1, name: { es: "Países Bajos", en: "Netherlands" } },
  { cc: 'NO', continent: 'europa', difficulty: 1, name: { es: "Noruega", en: "Norway" } },
  { cc: 'NP', continent: 'asia', difficulty: 2, name: { es: "Nepal", en: "Nepal" } },
  { cc: 'NR', continent: 'oceania', difficulty: 3, name: { es: "Nauru", en: "Nauru" } },
  { cc: 'NZ', continent: 'oceania', difficulty: 1, name: { es: "Nueva Zelanda", en: "New Zealand" } },
  { cc: 'OM', continent: 'asia', difficulty: 3, name: { es: "Omán", en: "Oman" } },
  { cc: 'PA', continent: 'america', difficulty: 2, name: { es: "Panamá", en: "Panama" } },
  { cc: 'PE', continent: 'america', difficulty: 1, name: { es: "Perú", en: "Peru" } },
  { cc: 'PG', continent: 'oceania', difficulty: 2, name: { es: "Papúa Nueva Guinea", en: "Papua New Guinea" } },
  { cc: 'PH', continent: 'asia', difficulty: 2, name: { es: "Filipinas", en: "Philippines" } },
  { cc: 'PK', continent: 'asia', difficulty: 2, name: { es: "Pakistán", en: "Pakistan" } },
  { cc: 'PL', continent: 'europa', difficulty: 1, name: { es: "Polonia", en: "Poland" } },
  { cc: 'PS', continent: 'asia', difficulty: 3, name: { es: "Territorios Palestinos", en: "Palestinian Territories" } },
  { cc: 'PT', continent: 'europa', difficulty: 1, name: { es: "Portugal", en: "Portugal" } },
  { cc: 'PW', continent: 'oceania', difficulty: 3, name: { es: "Palaos", en: "Palau" } },
  { cc: 'PY', continent: 'america', difficulty: 2, name: { es: "Paraguay", en: "Paraguay" } },
  { cc: 'QA', continent: 'asia', difficulty: 2, name: { es: "Catar", en: "Qatar" } },
  { cc: 'RO', continent: 'europa', difficulty: 2, name: { es: "Rumanía", en: "Romania" } },
  { cc: 'RS', continent: 'europa', difficulty: 2, name: { es: "Serbia", en: "Serbia" } },
  { cc: 'RU', continent: 'europa', difficulty: 1, name: { es: "Rusia", en: "Russia" } },
  { cc: 'RW', continent: 'africa', difficulty: 3, name: { es: "Ruanda", en: "Rwanda" } },
  { cc: 'SA', continent: 'asia', difficulty: 1, name: { es: "Arabia Saudí", en: "Saudi Arabia" } },
  { cc: 'SB', continent: 'oceania', difficulty: 3, name: { es: "Islas Salomón", en: "Solomon Islands" } },
  { cc: 'SC', continent: 'africa', difficulty: 3, name: { es: "Seychelles", en: "Seychelles" } },
  { cc: 'SD', continent: 'africa', difficulty: 2, name: { es: "Sudán", en: "Sudan" } },
  { cc: 'SE', continent: 'europa', difficulty: 1, name: { es: "Suecia", en: "Sweden" } },
  { cc: 'SG', continent: 'asia', difficulty: 2, name: { es: "Singapur", en: "Singapore" } },
  { cc: 'SI', continent: 'europa', difficulty: 2, name: { es: "Eslovenia", en: "Slovenia" } },
  { cc: 'SK', continent: 'europa', difficulty: 2, name: { es: "Eslovaquia", en: "Slovakia" } },
  { cc: 'SL', continent: 'africa', difficulty: 3, name: { es: "Sierra Leona", en: "Sierra Leone" } },
  { cc: 'SM', continent: 'europa', difficulty: 3, name: { es: "San Marino", en: "San Marino" } },
  { cc: 'SN', continent: 'africa', difficulty: 2, name: { es: "Senegal", en: "Senegal" } },
  { cc: 'SO', continent: 'africa', difficulty: 2, name: { es: "Somalia", en: "Somalia" } },
  { cc: 'SR', continent: 'america', difficulty: 3, name: { es: "Surinam", en: "Suriname" } },
  { cc: 'SS', continent: 'africa', difficulty: 3, name: { es: "Sudán del Sur", en: "South Sudan" } },
  { cc: 'ST', continent: 'africa', difficulty: 3, name: { es: "Santo Tomé y Príncipe", en: "São Tomé and Príncipe" } },
  { cc: 'SV', continent: 'america', difficulty: 2, name: { es: "El Salvador", en: "El Salvador" } },
  { cc: 'SY', continent: 'asia', difficulty: 2, name: { es: "Siria", en: "Syria" } },
  { cc: 'SZ', continent: 'africa', difficulty: 3, name: { es: "Esuatini", en: "Eswatini" } },
  { cc: 'TD', continent: 'africa', difficulty: 3, name: { es: "Chad", en: "Chad" } },
  { cc: 'TG', continent: 'africa', difficulty: 3, name: { es: "Togo", en: "Togo" } },
  { cc: 'TH', continent: 'asia', difficulty: 1, name: { es: "Tailandia", en: "Thailand" } },
  { cc: 'TJ', continent: 'asia', difficulty: 3, name: { es: "Tayikistán", en: "Tajikistan" } },
  { cc: 'TL', continent: 'asia', difficulty: 3, name: { es: "Timor-Leste", en: "Timor-Leste" } },
  { cc: 'TM', continent: 'asia', difficulty: 3, name: { es: "Turkmenistán", en: "Turkmenistan" } },
  { cc: 'TN', continent: 'africa', difficulty: 2, name: { es: "Túnez", en: "Tunisia" } },
  { cc: 'TO', continent: 'oceania', difficulty: 3, name: { es: "Tonga", en: "Tonga" } },
  { cc: 'TR', continent: 'asia', difficulty: 1, name: { es: "Turquía", en: "Türkiye" } },
  { cc: 'TT', continent: 'america', difficulty: 3, name: { es: "Trinidad y Tobago", en: "Trinidad and Tobago" } },
  { cc: 'TV', continent: 'oceania', difficulty: 3, name: { es: "Tuvalu", en: "Tuvalu" } },
  { cc: 'TZ', continent: 'africa', difficulty: 2, name: { es: "Tanzania", en: "Tanzania" } },
  { cc: 'UA', continent: 'europa', difficulty: 1, name: { es: "Ucrania", en: "Ukraine" } },
  { cc: 'UG', continent: 'africa', difficulty: 2, name: { es: "Uganda", en: "Uganda" } },
  { cc: 'US', continent: 'america', difficulty: 1, name: { es: "Estados Unidos", en: "United States" } },
  { cc: 'UY', continent: 'america', difficulty: 1, name: { es: "Uruguay", en: "Uruguay" } },
  { cc: 'UZ', continent: 'asia', difficulty: 3, name: { es: "Uzbekistán", en: "Uzbekistan" } },
  { cc: 'VA', continent: 'europa', difficulty: 2, name: { es: "Ciudad del Vaticano", en: "Vatican City" } },
  { cc: 'VC', continent: 'america', difficulty: 3, name: { es: "San Vicente y las Granadinas", en: "Saint Vincent and the Grenadines" } },
  { cc: 'VE', continent: 'america', difficulty: 1, name: { es: "Venezuela", en: "Venezuela" } },
  { cc: 'VN', continent: 'asia', difficulty: 1, name: { es: "Vietnam", en: "Vietnam" } },
  { cc: 'VU', continent: 'oceania', difficulty: 3, name: { es: "Vanuatu", en: "Vanuatu" } },
  { cc: 'WS', continent: 'oceania', difficulty: 3, name: { es: "Samoa", en: "Samoa" } },
  { cc: 'XK', continent: 'europa', difficulty: 3, name: { es: "Kosovo", en: "Kosovo" } },
  { cc: 'YE', continent: 'asia', difficulty: 3, name: { es: "Yemen", en: "Yemen" } },
  { cc: 'ZA', continent: 'africa', difficulty: 1, name: { es: "Sudáfrica", en: "South Africa" } },
  { cc: 'ZM', continent: 'africa', difficulty: 2, name: { es: "Zambia", en: "Zambia" } },
  { cc: 'ZW', continent: 'africa', difficulty: 2, name: { es: "Zimbabue", en: "Zimbabwe" } },
];
