const { withPodfile } = require('@expo/config-plugins');

const MARKER = '# @generated by withPodDeploymentTarget';

// Xcode 27 rejects pod targets that still declare iOS 9–13, even though the
// application already requires iOS 15.1. Keep each pod's higher minimum, if any.
const RUBY_PATCH = `
    ${MARKER}
    minimum_ios = Gem::Version.new(podfile_properties['ios.deploymentTarget'] || '15.1')
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
        current = configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        next unless current && current.match?(/\\A\\d+(?:\\.\\d+)*\\z/)
        if Gem::Version.new(current) < minimum_ios
          configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_ios.to_s
        end
      end
    end
`;

module.exports = function withPodDeploymentTarget(config) {
  return withPodfile(config, (podfileConfig) => {
    const podfile = podfileConfig.modResults.contents;
    if (podfile.includes(MARKER)) return podfileConfig;

    const postInstallEnd = /^(    react_native_post_install\([\s\S]*?^    \)\n)(  end\nend\s*$)/m;
    if (!postInstallEnd.test(podfile)) {
      throw new Error('withPodDeploymentTarget could not find the end of the CocoaPods post_install hook.');
    }
    podfileConfig.modResults.contents = podfile.replace(
      postInstallEnd,
      (_, reactNativePostInstall, end) => `${reactNativePostInstall}${RUBY_PATCH}${end}`
    );
    return podfileConfig;
  });
};
