const { withPodfile } = require('@expo/config-plugins');

const MARKER = '# @generated by withRevenueCatXcode27Fix';

// Swift in Xcode 27 synthesizes a memberwise initializer that collides with
// RevenueCat 5.67.1's throwing PaywallColor(stringRepresentation:) initializer.
// An initializer inside the struct suppresses that synthesized initializer.
const RUBY_PATCH = `    ${MARKER}
    revenuecat_color_file = File.join(installer.sandbox.root, 'RevenueCat', 'Sources', 'Paywalls', 'PaywallColor.swift')
    if File.exist?(revenuecat_color_file)
      source = File.read(revenuecat_color_file)
      anchor = '    fileprivate var _underlyingColor: (any Sendable)?'
      fix_marker = '// Suppress the synthesized memberwise initializer on Xcode 27.'
      unless source.include?(fix_marker)
        raise 'Unexpected RevenueCat PaywallColor layout' unless source.include?(anchor)

        replacement = [
          anchor,
          '',
          '    ' + fix_marker,
          '    private init() {',
          '        self.stringRepresentation = ""',
          '        self._underlyingColor = nil',
          '    }'
        ].join("\\n")
        File.chmod(0644, revenuecat_color_file)
        File.write(revenuecat_color_file, source.sub(anchor, replacement))
        Pod::UI.puts '[RevenueCat] Fixed PaywallColor initializer for Xcode 27'
      end
    end
`;

module.exports = function withRevenueCatXcode27Fix(config) {
  return withPodfile(config, (podfileConfig) => {
    const podfile = podfileConfig.modResults.contents;
    if (podfile.includes(MARKER)) return podfileConfig;

    const postInstallStart = /^(\s*)post_install do \|installer\|\s*$/m;
    if (!postInstallStart.test(podfile)) {
      throw new Error('withRevenueCatXcode27Fix could not find the CocoaPods post_install hook.');
    }
    podfileConfig.modResults.contents = podfile.replace(
      postInstallStart,
      (line) => `${line}\n${RUBY_PATCH}`
    );
    return podfileConfig;
  });
};
