const { withPodfile } = require('@expo/config-plugins');

const MARKER = '# @generated by withFmtConstevalFix';

const RUBY_PATCH = `    ${MARKER}
    fmt_base_header = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base_header)
      fmt_contents = File.read(fmt_base_header)
      fmt_patched_contents = fmt_contents.gsub(
        /#  define FMT_USE_CONSTEVAL 1/,
        '#  define FMT_USE_CONSTEVAL 0'
      )

      if fmt_patched_contents != fmt_contents
        File.chmod(0644, fmt_base_header)
        File.write(fmt_base_header, fmt_patched_contents)
        Pod::UI.puts '[fmt] Disabled FMT_USE_CONSTEVAL for Apple Clang compatibility'
      end
    end
`;

/**
 * Xcode 26.4 ships an Apple Clang version that rejects fmt 11.0.2's
 * consteval formatting path. React Native 0.81 pulls that fmt version when it
 * is built from source, so patch the downloaded pod during post_install.
 */
module.exports = function withFmtConstevalFix(config) {
  return withPodfile(config, (podfileConfig) => {
    const podfile = podfileConfig.modResults.contents;

    if (podfile.includes(MARKER)) {
      return podfileConfig;
    }

    const postInstallStart = /^(\s*)post_install do \|installer\|\s*$/m;
    if (!postInstallStart.test(podfile)) {
      throw new Error(
        'withFmtConstevalFix could not find the CocoaPods post_install hook.'
      );
    }

    podfileConfig.modResults.contents = podfile.replace(
      postInstallStart,
      (line) => `${line}\n${RUBY_PATCH}`
    );

    return podfileConfig;
  });
};
